name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x test.sh

      - name: Run test script
        run: ./test.sh
